import { SVG_MARGIN } from "../ClusterGraph/ClusterGraph.const";

import { CELL_HEIGHT } from "./CommitGraph.const";
import useHandleCommitGraph from "./CommitGraph.hook";
import type { CommitGraphNode } from "./CommitGraph.type";

const commits: CommitGraphNode[] = [
  {
    id: "111",
    parents: ["222"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "222",
    parents: ["444"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "333",
    parents: ["666"],
    stemId: "fix/git-remote-url-regex",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "444",
    parents: ["666"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "555",
    parents: ["666"],
    stemId: "feat/csm-with-pr",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "666",
    parents: ["777"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "777",
    parents: ["888"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "888",
    parents: ["999", "1111"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "999",
    parents: ["2222"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "1111",
    parents: ["2222"],
    stemId: "implicit-1",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "2222",
    parents: ["3333"],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
  {
    id: "3333",
    parents: [],
    stemId: "main",
    author: "",
    authorDate: "",
    branches: [""],
    committer: "",
    date: "",
    message: "",
    tags: [""],
  },
];

const CommitGraph = () => {
  const svgRef = useHandleCommitGraph({ commits });
  const svgHeight =
    commits.length * CELL_HEIGHT + SVG_MARGIN.top + SVG_MARGIN.bottom;

  return <svg className="cluster-graph" ref={svgRef} height={svgHeight} />;
};

export default CommitGraph;
