name: fix a bug 🐞
description: >-
  발견한 버그에 대한 정보를 입력해주세요.
title: '[fix]: '
labels:
  - fix
body:
  - type: textarea
    id: related-issue
    attributes:
        label: 관련 이슈
        description: 관련 있는 이슈 번호 기재 (#이슈번호)
        placeholder: >-
          #77
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 버그에 대해 명확하게 설명하여 주세요
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 참고
      description: 추가 논의사항 혹은 참고사항에 대해 기재해주세요