name: feature request 🚀
description: >-
  추가하고 싶은 신규 기능에 대해 알려주세요.
title: '[new feature]: '
labels:
  - new feature
body:
  - type: textarea
    id: related-issue
    attributes:
      label: 관련 이슈
      description: 관련 있는 이슈 번호 기재 (#이슈번호)
      placeholder: >-
        #77
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 기능에 대해 명확하게 설명하여 주세요
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: 기능 목록
      description: 기능 목록을 기재해주세요. 각 항목별로 새로운 줄에 입력하세요. (체크박스를 이용하면 좋아요)
      placeholder: >-
        - [ ] 기능 1
  - type: textarea
    id: reference
    attributes:
      label: 참고
      description: 추가 논의사항 혹은 참고사항에 대해 기재해주세요