name: test 🧪
description: >-
  테스트 사항에 대한 내용을 입력해주세요.
title: '[test]: '
labels:
  - test
body:
  - type: textarea
    id: related-issue
    attributes:
      label: 관련 이슈
      description: 관련 있는 이슈 번호 기재 (#이슈번호)
      placeholder: >-
        #77
  - type: textarea
    id: description
    attributes:
      label: 테스트 내용 설명
      description: 테스트 내용에 대해 명확하게 설명하여 주세요 (서술 혹은 스크린샷 첨부)
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 참고
      description: 추가 논의사항 혹은 참고사항에 대해 기재해주세요