name: Update docs ✍️
description: >-
 문서 업데이트가 필요한 경우 본 이슈를 사용하세요 (.md 파일 수정 등)

title: "[docs]: "
labels:
  - docs
body:
  - type: textarea
    id: description
    attributes:
      label: Related issue
      description: 관련 있는 이슈 번호 기재 (#이슈번호)
  - type: textarea
    id: context
    attributes:
      label: Content
      description: 본 이슈에 대한 내용을 작성해주세요.
    validations:
      required: true